apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: static
      image: abhijeetjha1995/multi-client:v4
      ports:
        - containerPort: 3000
