apiVersion: v1
kind: Pod
metadata:
  name: static-pod
  labels:
    component: web
spec:
  containers:
    - name: static
      image: abhijeetjha1995/multi-worker
      ports:
        - containerPort: 3000
