version: 2.1

orbs:
  aws-eks: circleci/aws-eks@2.2.0

jobs:
  test:
    machine:
      enabled: true
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Run Unit tests
          command: |
            docker build -t abhijeetjha1995/react-test -f ./client/Dockerfile.dev ./client
            docker run -e CI=true abhijeetjha1995/react-test npm test
  dockerImage: 
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Login Docker Hub and Upload image to Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
            docker build -t abhijeetjha1995/multi-client ./client
            docker build -t abhijeetjha1995/multi-nginx ./nginx
            docker build -t abhijeetjha1995/multi-server ./server
            docker build -t abhijeetjha1995/multi-worker ./worker
            docker push abhijeetjha1995/multi-client
            docker push abhijeetjha1995/multi-nginx
            docker push abhijeetjha1995/multi-server
            docker push abhijeetjha1995/multi-worker
  deploy:
    executor: aws-eks/python-3.8
    steps:
      - checkout
      - run:
          name: Configure AWS CLI
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region $AWS_DEFAULT_REGION
      - aws-eks/create-cluster:
          cluster-name: my-cluster
          version: "1.19"
      - aws-eks/update-kubeconfig:
          cluster-name: my-cluster
      - run:
          name: Apply Deployment Manifest
          command: |
            kubectl apply -f deployment.yml


workflows:
  version: 2.1
  build-test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master